name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust server fingerprint
        run: |
          mkdir -p ~/.ssh
          echo "5.129.197.158 ssh-ed25519 SHA256:w981K0Fau9rQU4tq6GHbLiRY4ZDdhbWmKATmJGh0ZQU" >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh root@5.129.197.158 << 'EOF'
          cd /var/www/verstack-web
          pm2 stop verstack
          git pull origin main
          npm install
          npm run build
          pm2 start verstack --update-env
          pm2 status
          EOF