name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Stopping pm2 process"
            pm2 stop my-app || true

            echo "Go to project directory"
            cd /path/to/your/project

            echo "Pulling latest changes"
            git pull origin main

            echo "Installing dependencies and building"
            npm install
            npm run build

            echo "Starting pm2 process"
            pm2 start npm --name "my-app" -- start
